declare const __UI_HTML__: string;

import { applyDiffSelections } from "../core/apply.js";
import { assertGitHubSettings, getMissingGitHubSettings, normalizePluginConfig } from "../core/config.js";
import { diffSyncDocuments } from "../core/diff.js";
import { buildPullRequestFiles, type PullRequestFiles } from "../core/export.js";
import { GitHubClient } from "../core/github.js";
import { hasResolutionDirection } from "../core/resolutions.js";
import type { PluginConfig, SyncDocument } from "../core/types.js";
import type { PluginRequest, PluginResponse } from "../shared/messages.js";
import { describeError } from "./describe-error.js";
import { applySyncDocumentToFigma, readLocalSyncDocument } from "./figma.js";
import { createSequentialMessageHandler } from "./request-queue.js";
import { readStoredConfig, readStoredToken, writeStoredConfig, writeStoredToken } from "./storage.js";

type RuntimeState = {
  config: PluginConfig;
  token: string;
  figmaDocument?: SyncDocument;
  repoDocument?: SyncDocument;
  diffs?: ReturnType<typeof diffSyncDocuments>;
};

const runtimeState: RuntimeState = {
  config: readStoredConfig(),
  token: ""
};

figma.showUI(__UI_HTML__, { width: 640, height: 640, themeColors: true });

function postMessage(message: PluginResponse): void {
  figma.ui.postMessage(message);
}

function postStatus(level: "info" | "success" | "warning", message: string): void {
  postMessage({ type: "status", level, message });
}

function createGitHubClient(config: PluginConfig, token: string): GitHubClient {
  assertGitHubSettings(config, token);
  const normalized = normalizePluginConfig(config);

  return new GitHubClient({
    owner: normalized.owner,
    repo: normalized.repo,
    baseBranch: normalized.baseBranch,
    token: token.trim()
  });
}

function createBranchName(): string {
  const timestamp = new Date().toISOString().replace(/[-:]/g, "").replace(/\..+/, "").replace("T", "-");
  return `sync/${timestamp.toLowerCase()}`;
}

function canRefreshMapping(config: PluginConfig, token: string): boolean {
  return getMissingGitHubSettings(config, token).length === 0;
}

async function refreshFigmaState(): Promise<SyncDocument> {
  const document = await readLocalSyncDocument();
  runtimeState.figmaDocument = document;
  postMessage({ type: "state", state: { figmaDocument: document } });
  return document;
}

async function refreshRepoState(config: PluginConfig, token: string): Promise<SyncDocument> {
  const client = createGitHubClient(config, token);
  const document = await client.readSyncDocument(config.targetDir);
  runtimeState.repoDocument = document;
  postMessage({ type: "state", state: { repoDocument: document } });
  return document;
}

async function computeDiff(config: PluginConfig, token: string): Promise<void> {
  const figmaDocument = runtimeState.figmaDocument ?? (await refreshFigmaState());
  const repoDocument = runtimeState.repoDocument ?? (await refreshRepoState(config, token));
  const diffs = diffSyncDocuments(figmaDocument, repoDocument);
  runtimeState.diffs = diffs;
  postMessage({ type: "state", state: { figmaDocument, repoDocument, diffs } });
}

async function refreshDiff(config: PluginConfig, token: string): Promise<void> {
  const figmaDocument = await refreshFigmaState();
  const repoDocument = await refreshRepoState(config, token);
  const diffs = diffSyncDocuments(figmaDocument, repoDocument);
  runtimeState.diffs = diffs;
  postMessage({ type: "state", state: { figmaDocument, repoDocument, diffs } });
}

async function createPullRequest(config: PluginConfig, token: string, document: SyncDocument, titlePrefix: string) {
  const client = createGitHubClient(config, token);
  // 残った古いファイルの検出（#23）のため、base branch 上の現状ファイルを取得してから PR 内容を組む
  const repoFiles = await client.readRepoFiles(config.targetDir);
  await createPullRequestWithFiles(
    config,
    token,
    buildPullRequestFiles({ document, targetDir: config.targetDir, repoFiles }),
    titlePrefix
  );
}

async function createPullRequestWithFiles(
  config: PluginConfig,
  token: string,
  { files, deletePaths }: PullRequestFiles,
  titlePrefix: string
) {
  const client = createGitHubClient(config, token);
  const branchName = createBranchName();
  const pullRequest = await client.createPullRequestFromFiles({
    branchName,
    title: `${titlePrefix} ${new Date().toLocaleString("ja-JP")}`,
    body: "Generated by Figma Variable Sync plugin.",
    files,
    deletePaths
  });

  postMessage({ type: "state", state: { pullRequest } });
  postStatus("success", `PR #${pullRequest.number} を作成しました。`);
}

function selectedDeleteIds(
  diffs: ReturnType<typeof diffSyncDocuments>,
  resolutions: Record<string, "figma-to-repo" | "repo-to-figma" | "skip">
): { deleteVariableIds: string[]; deleteStyleIds: string[] } {
  const deleteVariableIds: string[] = [];
  const deleteStyleIds: string[] = [];

  for (const diff of diffs) {
    if (
      diff.changeKind !== "delete" ||
      diff.details.missingSide !== "repo" ||
      (resolutions[diff.resolutionId] ?? "skip") !== "repo-to-figma"
    ) {
      continue;
    }

    if (diff.entityKind === "variable") {
      deleteVariableIds.push(diff.figmaId);
    } else if (diff.entityKind === "style") {
      deleteStyleIds.push(diff.figmaId);
    }
  }

  return { deleteVariableIds, deleteStyleIds };
}

async function handleRequest(message: PluginRequest): Promise<void> {
  switch (message.type) {
    case "load-initial-state": {
      runtimeState.token = await readStoredToken();
      const figmaDocument = await refreshFigmaState();
      postMessage({
        type: "state",
        state: {
          config: runtimeState.config,
          hasStoredToken: Boolean(runtimeState.token),
          figmaDocument
        }
      });
      if (canRefreshMapping(runtimeState.config, runtimeState.token)) {
        const repoDocument = await refreshRepoState(runtimeState.config, runtimeState.token);
        const diffs = diffSyncDocuments(figmaDocument, repoDocument);
        runtimeState.diffs = diffs;
        postMessage({ type: "state", state: { repoDocument, diffs } });
        postStatus("info", "Figma と GitHub からデータを読み込み、対応表を更新しました。");
      }
      return;
    }
    case "save-config": {
      const nextToken = message.token || runtimeState.token;
      runtimeState.config = { ...normalizePluginConfig(message.config), patStorageOptIn: true };
      runtimeState.token = nextToken.trim();
      writeStoredConfig(runtimeState.config);
      await writeStoredToken(runtimeState.token, true);
      postMessage({
        type: "state",
        state: {
          config: runtimeState.config,
          hasStoredToken: Boolean(runtimeState.token)
        }
      });
      postStatus("success", "設定を保存しました。");
      return;
    }
    case "resize-window": {
      figma.ui.resize(Math.round(message.width), Math.round(message.height));
      return;
    }
    case "refresh-diff": {
      runtimeState.config = message.config;
      await refreshDiff(message.config, runtimeState.token);
      postStatus("info", "Figma と GitHub からデータを読み込み、対応表を更新しました。");
      return;
    }
    case "scan-figma": {
      await refreshFigmaState();
      postStatus("success", "Figma の local variables/styles を読み込みました。");
      return;
    }
    case "load-repo": {
      runtimeState.config = message.config;
      await refreshRepoState(message.config, runtimeState.token);
      postStatus("success", "GitHub の JSON を読み込みました。");
      return;
    }
    case "compute-diff": {
      runtimeState.config = message.config;
      await computeDiff(message.config, runtimeState.token);
      postStatus("info", "対応表を更新しました。");
      return;
    }
    case "export-figma-to-github": {
      runtimeState.config = message.config;
      const figmaDocument = await refreshFigmaState();
      await createPullRequest(message.config, runtimeState.token, figmaDocument, "Sync Figma tokens");
      return;
    }
    case "import-repo-to-figma": {
      runtimeState.config = message.config;
      const repoDocument = await refreshRepoState(message.config, runtimeState.token);
      const warnings = await applySyncDocumentToFigma(repoDocument);
      const figmaDocument = await refreshFigmaState();
      const diffs = diffSyncDocuments(figmaDocument, repoDocument);
      runtimeState.diffs = diffs;
      postMessage({ type: "state", state: { figmaDocument, repoDocument, diffs } });
      if (warnings.length > 0) {
        postStatus("warning", `${warnings.length} 件の warning があります。`);
      } else {
        postStatus("success", "GitHub の JSON を Figma に反映しました。");
      }
      return;
    }
    case "apply-selected": {
      runtimeState.config = message.config;
      const figmaDocument = runtimeState.figmaDocument ?? (await refreshFigmaState());
      const repoDocument = runtimeState.repoDocument ?? (await refreshRepoState(message.config, runtimeState.token));
      const diffs = runtimeState.diffs ?? diffSyncDocuments(figmaDocument, repoDocument);
      const applied = applyDiffSelections({
        figmaDocument,
        repoDocument,
        diffs,
        resolutions: message.resolutions
      });
      const hasRepoToFigma = hasResolutionDirection(diffs, message.resolutions, "repo-to-figma");
      const hasFigmaToRepo = hasResolutionDirection(diffs, message.resolutions, "figma-to-repo");
      const deleteIds = selectedDeleteIds(diffs, message.resolutions);

      const warnings = hasRepoToFigma
        ? await applySyncDocumentToFigma(applied.figmaDocument, deleteIds)
        : [];
      const refreshedFigmaDocument = hasRepoToFigma ? await refreshFigmaState() : figmaDocument;
      runtimeState.diffs = diffSyncDocuments(refreshedFigmaDocument, repoDocument);
      postMessage({
        type: "state",
        state: {
          figmaDocument: refreshedFigmaDocument,
          repoDocument,
          diffs: runtimeState.diffs
        }
      });

      if (hasFigmaToRepo) {
        // 部分適用でも、対象コレクションの古いファイルは削除する（#23）
        const client = createGitHubClient(message.config, runtimeState.token);
        const repoFiles = await client.readRepoFiles(message.config.targetDir);
        await createPullRequestWithFiles(
          message.config,
          runtimeState.token,
          buildPullRequestFiles({
            document: applied.repoDocument,
            targetDir: message.config.targetDir,
            diffs,
            resolutions: message.resolutions,
            repoFiles
          }),
          "Sync selected token changes"
        );
      }
      if (warnings.length > 0) {
        postStatus("warning", `${warnings.length} 件の warning があります。`);
      }
      return;
    }
  }
}

figma.ui.onmessage = createSequentialMessageHandler(handleRequest, (error) => {
  // devtools には全文（スタック含む）を残し、UI には可能な限り中身のある文言を出す。
  console.error("[token-bridge-figma] request failed:", error);
  postMessage({
    type: "error",
    message: describeError(error)
  });
});
