import test from "node:test";
import assert from "node:assert/strict";

import { GitHubClient } from "../src/core/github.js";

test("GitHubClient creates branch, upserts files, and creates pull request", async () => {
  const calls: Array<{ url: string; options: RequestInit }> = [];
  const client = new GitHubClient({
    owner: "acme",
    repo: "tokens",
    baseBranch: "main",
    token: "secret",
    fetchImpl: async (url, options) => {
      calls.push({ url: String(url), options: options ?? {} });

      if (String(url).endsWith("/git/ref/heads/main")) {
        return new Response(JSON.stringify({ object: { sha: "base-sha" } }), { status: 200 });
      }

      if (String(url).endsWith("/git/refs")) {
        return new Response(JSON.stringify({ ref: "refs/heads/sync/test" }), { status: 201 });
      }

      if (String(url).endsWith("/git/commits/base-sha")) {
        return new Response(JSON.stringify({ tree: { sha: "base-tree-sha" } }), { status: 200 });
      }

      if (String(url).endsWith("/git/trees") && options?.method === "POST") {
        return new Response(JSON.stringify({ sha: "next-tree-sha" }), { status: 201 });
      }

      if (String(url).endsWith("/git/commits") && options?.method === "POST") {
        return new Response(JSON.stringify({ sha: "next-commit-sha" }), { status: 201 });
      }

      if (String(url).endsWith("/git/refs/heads/sync%2Ftest") && options?.method === "PATCH") {
        return new Response(JSON.stringify({ ref: "refs/heads/sync/test" }), { status: 200 });
      }

      if (String(url).endsWith("/pulls")) {
        return new Response(JSON.stringify({ number: 42, html_url: "https://example.com/pr/42" }), { status: 201 });
      }

      throw new Error(`unexpected url: ${String(url)}`);
    }
  });

  const result = await client.createPullRequestFromFiles({
    branchName: "sync/test",
    title: "Sync tokens",
    body: "Generated by plugin",
    files: {
      "tokens/variables/semantic.json": "{\n  \"ok\": true\n}"
    }
  });

  assert.equal(result.number, 42);
  assert.equal(calls.length, 7);
  assert.match(String(calls[1]!.options.body), /refs\/heads\/sync\/test/);
  assert.equal(calls[2]!.options.method, "GET");
  assert.match(calls[2]!.url, /\/git\/commits\/base-sha$/);
  assert.equal(calls[3]!.options.method, "POST");
  assert.match(calls[3]!.url, /\/git\/trees$/);
  assert.match(String(calls[3]!.options.body), /"base_tree":"base-tree-sha"/);
  assert.match(String(calls[3]!.options.body), /"path":"tokens\/variables\/semantic\.json"/);
  assert.match(String(calls[3]!.options.body), /"content":"\{\\n  \\"ok\\": true\\n\}"/);
  assert.equal(calls[4]!.options.method, "POST");
  assert.match(calls[4]!.url, /\/git\/commits$/);
  assert.match(String(calls[4]!.options.body), /"tree":"next-tree-sha"/);
  assert.equal(calls[5]!.options.method, "PATCH");
  assert.match(calls[5]!.url, /\/git\/refs\/heads\/sync%2Ftest$/);
});

test("GitHubClient encodes and decodes UTF-8 content without TextEncoder", async () => {
  const payload = "{\n  \"label\": \"日本語\"\n}";
  const encodedPayload = Buffer.from(payload, "utf8").toString("base64");
  const calls: Array<{ url: string; options: RequestInit }> = [];

  const client = new GitHubClient({
    owner: "acme",
    repo: "tokens",
    baseBranch: "main",
    token: "secret",
    fetchImpl: async (url, options) => {
      calls.push({ url: String(url), options: options ?? {} });

      if (String(url).endsWith("/git/ref/heads/main")) {
        return new Response(JSON.stringify({ object: { sha: "base-sha" } }), { status: 200 });
      }

      if (String(url).endsWith("/git/commits/base-sha")) {
        return new Response(JSON.stringify({ tree: { sha: "tree-sha" } }), { status: 200 });
      }

      if (String(url).includes("/git/trees/tree-sha")) {
        return new Response(
          JSON.stringify({
            tree: [{ path: "tokens/variables/semantic.json", type: "blob", sha: "blob-sha" }]
          }),
          { status: 200 }
        );
      }

      if (String(url).endsWith("/git/blobs/blob-sha")) {
        return new Response(JSON.stringify({ content: `${encodedPayload}\n` }), { status: 200 });
      }

      if (String(url).includes("/contents/") && options?.method === "GET") {
        return new Response(JSON.stringify({ message: "Not Found" }), { status: 404 });
      }

      if (String(url).includes("/contents/") && options?.method === "PUT") {
        return new Response(JSON.stringify({ content: { path: "ok" } }), { status: 200 });
      }

      throw new Error(`unexpected url: ${String(url)}`);
    }
  });

  const files = await client.readRepoFiles("tokens");
  assert.equal(files["tokens/variables/semantic.json"], payload);

  await client.upsertFile({
    path: "tokens/variables/semantic.json",
    content: payload,
    branch: "main",
    message: "Sync utf8"
  });

  const putCall = calls.find((call) => call.options.method === "PUT");
  assert.ok(putCall);
  const putBody = JSON.parse(String(putCall.options.body)) as { content: string };
  assert.equal(putBody.content, encodedPayload);
});

test("GitHubClient fallback base64 works without Buffer or browser helpers", async () => {
  const originalBuffer = globalThis.Buffer;
  const originalBtoa = (globalThis as typeof globalThis & { btoa?: unknown }).btoa;
  const originalAtob = (globalThis as typeof globalThis & { atob?: unknown }).atob;
  const payload = "{\n  \"label\": \"日本語\"\n}";
  const encodedPayload = Buffer.from(payload, "utf8").toString("base64");
  const response = (status: number, jsonPayload: unknown, textPayload = JSON.stringify(jsonPayload)) =>
    ({
      status,
      json: async () => jsonPayload,
      text: async () => textPayload
    }) as Response;

  try {
    Reflect.set(globalThis, "Buffer", undefined);
    Reflect.set(globalThis, "btoa", undefined);
    Reflect.set(globalThis, "atob", undefined);
    const calls: Array<{ url: string; options: RequestInit }> = [];

    const client = new GitHubClient({
      owner: "acme",
      repo: "tokens",
      baseBranch: "main",
      token: "secret",
      fetchImpl: async (url, options) => {
        calls.push({ url: String(url), options: options ?? {} });

        if (String(url).endsWith("/git/ref/heads/main")) {
          return response(200, { object: { sha: "base-sha" } });
        }

        if (String(url).endsWith("/git/commits/base-sha")) {
          return response(200, { tree: { sha: "tree-sha" } });
        }

        if (String(url).includes("/git/trees/tree-sha")) {
          return response(200, {
            tree: [{ path: "tokens/variables/semantic.json", type: "blob", sha: "blob-sha" }]
          });
        }

        if (String(url).endsWith("/git/blobs/blob-sha")) {
          return response(200, { content: `${encodedPayload}\n` });
        }

        if (String(url).includes("/contents/") && options?.method === "GET") {
          return response(404, { message: "Not Found" });
        }

        if (String(url).includes("/contents/") && options?.method === "PUT") {
          return response(200, { content: { path: "ok" } });
        }

        throw new Error(`unexpected url: ${String(url)}`);
      }
    });

    const files = await client.readRepoFiles("tokens");
    assert.equal(files["tokens/variables/semantic.json"], payload);

    await client.upsertFile({
      path: "tokens/variables/semantic.json",
      content: payload,
      branch: "main",
      message: "Sync utf8 fallback"
    });

    const putCall = calls.find((call) => call.options.method === "PUT");
    assert.ok(putCall);
    const putBody = JSON.parse(String(putCall.options.body)) as { content: string };
    assert.equal(putBody.content, encodedPayload);
  } finally {
    Reflect.set(globalThis, "Buffer", originalBuffer);
    Reflect.set(globalThis, "btoa", originalBtoa);
    Reflect.set(globalThis, "atob", originalAtob);
  }
});

// #23: 残り続ける古いファイルの削除を PR に含める（Git tree API の sha: null エントリ）
test("GitHubClient includes deletions in the pull request tree (#23)", async () => {
  const calls: Array<{ url: string; options: RequestInit }> = [];
  const client = new GitHubClient({
    owner: "acme",
    repo: "tokens",
    baseBranch: "main",
    token: "secret",
    fetchImpl: async (url, options) => {
      calls.push({ url: String(url), options: options ?? {} });
      if (String(url).endsWith("/git/ref/heads/main")) {
        return new Response(JSON.stringify({ object: { sha: "base-sha" } }), { status: 200 });
      }
      if (String(url).endsWith("/git/refs")) {
        return new Response(JSON.stringify({ ref: "refs/heads/sync/test" }), { status: 201 });
      }
      if (String(url).endsWith("/git/commits/base-sha")) {
        return new Response(JSON.stringify({ tree: { sha: "base-tree-sha" } }), { status: 200 });
      }
      if (String(url).endsWith("/git/trees") && options?.method === "POST") {
        return new Response(JSON.stringify({ sha: "next-tree-sha" }), { status: 201 });
      }
      if (String(url).endsWith("/git/commits") && options?.method === "POST") {
        return new Response(JSON.stringify({ sha: "next-commit-sha" }), { status: 201 });
      }
      if (String(url).includes("/git/refs/heads/") && options?.method === "PATCH") {
        return new Response(JSON.stringify({ ref: "refs/heads/sync/test" }), { status: 200 });
      }
      if (String(url).endsWith("/pulls")) {
        return new Response(JSON.stringify({ number: 43, html_url: "https://example.com/pr/43" }), { status: 201 });
      }
      throw new Error(`unexpected url: ${String(url)}`);
    }
  });

  await client.createPullRequestFromFiles({
    branchName: "sync/test",
    title: "Sync tokens",
    body: "Generated by plugin",
    files: { "tokens/variables/deprecated-dimension.json": "{}" },
    deletePaths: ["tokens/variables/dimension.json"]
  });

  const treeCall = calls.find((c) => c.url.endsWith("/git/trees"));
  const body = JSON.parse(String(treeCall!.options.body)) as {
    tree: Array<{ path: string; sha?: string | null; content?: string }>;
  };
  const deletion = body.tree.find((e) => e.path === "tokens/variables/dimension.json");
  assert.ok(deletion, "削除エントリが tree に含まれる");
  assert.equal(deletion!.sha, null);
  assert.equal("content" in deletion!, false);
  const addition = body.tree.find((e) => e.path === "tokens/variables/deprecated-dimension.json");
  assert.equal(addition!.content, "{}");
});
